apiVersion: v1
kind: Service
metadata:
  name: fake-news-service
  namespace: fake-news
spec:
  type: NodePort
  selector:
    app: fake-news
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30080
