apiVersion: v1
kind: Service
metadata:
  name: face-mask-service
  namespace: face-mask
spec:
  type: NodePort
  selector:
    app: face-mask
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30080
